from . import Inlinebutton
from . import callback_data
from . import web_kurslar
from . import Mobile
from . import Desktop
from . import Computer_graphics
from . import Computer_science
from . import web_mentor
from . import Mobile_mentor
from . import Deskop_mentor
